version: '3'
services:
    nginx:
        image: jwilder/nginx-proxy:alpine
        network_mode: bridge
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
